### ISSUE TITLE
missing required active authority when run hive.broadcast.transfer

### ISSUE THREAD

**Issue by past2017** [openhive-network/hivejs#12]
run below code:
```
var hivejs = require('@hivechain/hivejs');
hivejs.api.setOptions({ url: 'https://api.openhive.network' });
var user="test360"
var password="o6LcmppatgC5p73F429ro2oGBmiIMkuU"
var from="test360"
var to="test3611"
var amount="1.000 HIVE"
var memo="222"

var privWif = hivejs.auth.toWif(user, password, 'active');
hivejs.broadcast.transfer(privWif, from, to, amount, memo, function(err, result) {
      console.log(err, result);
});
```
i can use this user and password login hive.blog, i completely confirm this passowrd is right,but when i run this code, some error reported
```
{ RPCError: missing required active authority:Missing Active Authority test360
    at new RPCError (/root/test/node_modules/@hivechain/hivejs/lib/api/transports/http.js:43:106)
    at /root/test/node_modules/@hivechain/hivejs/lib/api/transports/http.js:93:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
  cause:
   { RPCError: missing required active authority:Missing Active Authority test360
       at new RPCError (/root/test/node_modules/@hivechain/hivejs/lib/api/transports/http.js:43:106)
       at /root/test/node_modules/@hivechain/hivejs/lib/api/transports/http.js:93:13
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'RPCError',
     code: -32000,
     data:
      { code: 3010000,
        name: 'tx_missing_active_auth',
        message: 'missing required active authority',
        stack: [Array] } },
  isOperational: true,
  code: -32000,
  data:
   { code: 3010000,
     name: 'tx_missing_active_auth',
     message: 'missing required active authority',
     stack: [ [Object], [Object], [Object], [Object], [Object] ] } } undefined


```

**Comment by roelandp** [comment]
please use https://gitlab.syncad.com/hive/hive-js and see if that fixes things...

**Comment by past2017** [comment]
run below code
```
var hivejs = require('steem');
hivejs.api.setOptions({ url: 'https://api.openhive.network' });
var user="test360"
var password="o6LcmppatgC5p73F429ro2oGBmiIMkuU"
var from="test360"
var to="test3611"
var amount="1.000 HIVE"
var memo="222"

var privWif = hivejs.auth.toWif(user, password, 'active');
hivejs.broadcast.transfer(privWif, from, to, amount, memo, function(err, result) {
      console.log(err, result);
});
```
same error report
```
{ RPCError: missing required active authority:Missing Active Authority test360
    at new RPCError (/root/steem/node_modules/steem/lib/api/transports/http.js:43:106)
    at /root/steem/node_modules/steem/lib/api/transports/http.js:93:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
  cause:
   { RPCError: missing required active authority:Missing Active Authority test360
       at new RPCError (/root/steem/node_modules/steem/lib/api/transports/http.js:43:106)
       at /root/steem/node_modules/steem/lib/api/transports/http.js:93:13
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'RPCError',
     code: -32000,
     data:
      { code: 3010000,
        name: 'tx_missing_active_auth',
        message: 'missing required active authority',
        stack: [Array] } },
  isOperational: true,
  code: -32000,
  data:
   { code: 3010000,
     name: 'tx_missing_active_auth',
     message: 'missing required active authority',
     stack: [ [Object], [Object], [Object], [Object], [Object] ] } } undefined
```

**Comment by past2017** [comment]
@roelandp I am developer working on an exchange, we want interagte HIVE to our exchange, please help me to solve this transfer issue, thanks

**Comment by roelandp** [comment]
please use https://gitlab.syncad.com/hive/hive-js also for any issues... I will now unsubscribe. 

if you have an exchange, please let us know your official email so we can reach out or via telegram.

**Comment by roelandp** [comment]
https://developers.hive.io/tutorials-javascript/transfer_steem_and_sbd.html 

please note some need Steem / SBD replaced with HIVE/HBD !

**Comment by past2017** [comment]
@roelandp 
my email is jiaju@mxc.com 
please help me, thank you

**Comment by roelandp** [comment]
@feruzm  is looking into it atm. stay tuned. thx! as we literally just shifted chains we are still amidst updating all libraries. Afaik this was already fixed, yet this repo might have the wrong version or maybe not even a newly generated distro. Or maybe the wrong library is included in your script... 

Give us a little time, back with you asap.

**Comment by past2017** [comment]
@roelandp got it, thank you very much

**Comment by feruzm** [comment]
@past2017 

Please try with `dhive` library for now, until we fix issue on `hivejs`.

Here is an example with dhive:

```
var dhive = require('@hivechain/dhive');
var client = new dhive.Client('https://api.hive.blog', {
  timeout: 3000,
});

var privateKey = dhive.PrivateKey.fromLogin(user, password, 'active')

const args = {
  from: from,
  to: to,
  amount: amount,
  memo: memo,
};

client.broadcast
  .transfer(args, privateKey)
  .then((result) => {
    if (result) {
      console.log(result);
    }
  })
  .catch((err) => {
    console.log(err);
  });
```

**Comment by past2017** [comment]
@feruzm @roelandp we have transfer successfully, thank you so much
by the way could you please pull me to a telegram team, maybe another question need your help, thank you again
for example: I want to create a new account by API, i thought i should use https://github.com/openhive-network/hivejs/tree/master/doc#account-create
but it looks this may not work well, so is there an alternative one?

**Comment by feruzm** [comment]
@past2017  we have now fixed transfer issues. Please test your scripts with latest version (`1.0.4`) of `@hivechain/hivejs`

Account create api should work, note that it requires ~3 HIVE to create an account. Alternative is to [create account with HP delegation](https://github.com/openhive-network/hivejs/tree/master/doc#account-create-with-delegation), another alternative is to create account by claiming account credits which then allows you to create account for free with minimal resources.
https://signup.hive.io has some easy to use user interfaces offered by our community members.

**Comment by past2017** [comment]
@feruzm got it, thank you so much
another issue, please give me a suggestion about which api i should use: dhive or hivejs?
